name: Java CI/CD

on:
  push:
    branches:
      - cicd
  pull_request:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Test mspatient with Maven
        run: mvn -B test --file mspatient/pom.xml

      - name: Test mshopital with Maven
        run: mvn -B test --file mshopital/pom.xml

      - name: Test with Maven (msreservation)
        run: mvn -B test --file msreservation/pom.xml

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build mspatient with Maven
        run: mvn -B package --file mspatient/pom.xml

      - name: Build mshopital with Maven
        run: mvn -B package --file mshopital/pom.xml

      - name: Build with Maven (msreservation)
        run: mvn -B package --file msreservation/pom.xml


  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: '20.5.1'

      - name: Install dependencies
        run: |
          cd PocFrontEnd
          npm install

      - name: Build frontend
        run: |
          cd PocFrontEnd
          npm run build


      - name: Run E2E tests
        run: |
          cd PocFrontEnd
          npm run dev --verbose